workflows:
  idris-schools-ios-testflight-workflow:
    name: IDRIS Schools iOS Build and Publish to TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      # نفس الـ integration المضافة في حسابك على كودماجيك
      app_store_connect: noourway

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        provisioning_profiles:
          - IDRIS_Schools_Profile # اسم البروفايل الجديد الخاص بـ IDRIS Schools
        certificates:
          - ios_cert_manual # نفس اسم الشهادة (Certificate) السابقة بما أنه نفس الحساب المطور

    scripts:
      - name: Set iOS deployment target
        script: |
          # تعديل الحد الأدنى للإصدار
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' "s/^platform :ios, .*/platform :ios, '15.0'/g" ios/Podfile
          sed -i '' "s/^# platform :ios, .*/platform :ios, '15.0'/g" ios/Podfile

      - name: Clean and Get Dependencies
        script: |
          # تعطيل Swift Package Manager من إعدادات فلاتر لتجاوز خطأ الـ PBXGroup
          flutter config --no-enable-swift-package-manager

          flutter clean
          flutter pub upgrade
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod repo update
          pod install

      - name: Apply Vault Profiles
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          # العودة للأمر الأصلي النظيف
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - codexus.eg@gmail.com
