name: idris_school_app
description: Idris School mobile application.
publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  file_picker: ^8.1.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_white_1024.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  config:
    enable-swift-package-manager: false

  assets:
    - assets/images/splash_logo.png
    - assets/images/app_icon_1024.png
    - assets/images/app_icon_foreground.png
    - assets/images/app_icon_white_1024.png
